//! RPC call identifiers used in the Among Us protocol.
//!
//! Each RPC call targets a specific InnerNetObject (identified by NetId)
//! and carries parameters specific to that RPC.

/// All RPC calls in the Among Us protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum RpcCalls {
    PlayAnimation = 0,
    CompleteTask = 1,
    SyncSettings = 2,
    SetInfected = 3,
    Exiled = 4,
    CheckName = 5,
    SetName = 6,
    CheckColor = 7,
    SetColor = 8,
    SetHat = 9,
    SetSkin = 10,
    ReportDeadBody = 11,
    MurderPlayer = 12,
    SendChat = 13,
    StartMeeting = 14,
    SetScanner = 15,
    SendChatNote = 16,
    SetPet = 17,
    SetStartCounter = 18,
    EnterVent = 19,
    ExitVent = 20,
    SnapTo = 21,
    CloseMeeting = 22,
    VotingComplete = 23,
    CastVote = 24,
    ClearVote = 25,
    AddVote = 26,
    CloseDoorsOfType = 27,
    SetTasks = 29,
    ClimbLadder = 31,
    UsePlatform = 32,
    SendQuickChat = 33,
    BootFromVent = 34,
    UpdateSystem = 35,
    SetVisor = 36,
    SetNamePlate = 37,
    SetLevel = 38,
    SetHatStr = 39,
    SetSkinStr = 40,
    SetPetStr = 41,
    SetVisorStr = 42,
    SetNamePlateStr = 43,
    SetRole = 44,
    ProtectPlayer = 45,
    Shapeshift = 46,
    CheckMurder = 47,
    CheckProtect = 48,
    Pet = 49,
    CancelPet = 50,
    CheckZipline = 51,
    UseZipline = 52,
    TriggerSpores = 53,
    CheckSpore = 54,
    CheckShapeshift = 55,
    RejectShapeshift = 56,
    LobbyTimeExpiring = 60,
    ExtendLobbyTimer = 61,
    CheckVanish = 62,
    StartVanish = 63,
    CheckAppear = 64,
    StartAppear = 65,
}

impl RpcCalls {
    /// Try to convert a byte to an RpcCalls variant.
    pub fn from_byte(byte: u8) -> Option<Self> {
        match byte {
            0 => Some(Self::PlayAnimation),
            1 => Some(Self::CompleteTask),
            2 => Some(Self::SyncSettings),
            3 => Some(Self::SetInfected),
            4 => Some(Self::Exiled),
            5 => Some(Self::CheckName),
            6 => Some(Self::SetName),
            7 => Some(Self::CheckColor),
            8 => Some(Self::SetColor),
            9 => Some(Self::SetHat),
            10 => Some(Self::SetSkin),
            11 => Some(Self::ReportDeadBody),
            12 => Some(Self::MurderPlayer),
            13 => Some(Self::SendChat),
            14 => Some(Self::StartMeeting),
            15 => Some(Self::SetScanner),
            16 => Some(Self::SendChatNote),
            17 => Some(Self::SetPet),
            18 => Some(Self::SetStartCounter),
            19 => Some(Self::EnterVent),
            20 => Some(Self::ExitVent),
            21 => Some(Self::SnapTo),
            22 => Some(Self::CloseMeeting),
            23 => Some(Self::VotingComplete),
            24 => Some(Self::CastVote),
            25 => Some(Self::ClearVote),
            26 => Some(Self::AddVote),
            27 => Some(Self::CloseDoorsOfType),
            29 => Some(Self::SetTasks),
            31 => Some(Self::ClimbLadder),
            32 => Some(Self::UsePlatform),
            33 => Some(Self::SendQuickChat),
            34 => Some(Self::BootFromVent),
            35 => Some(Self::UpdateSystem),
            36 => Some(Self::SetVisor),
            37 => Some(Self::SetNamePlate),
            38 => Some(Self::SetLevel),
            39 => Some(Self::SetHatStr),
            40 => Some(Self::SetSkinStr),
            41 => Some(Self::SetPetStr),
            42 => Some(Self::SetVisorStr),
            43 => Some(Self::SetNamePlateStr),
            44 => Some(Self::SetRole),
            45 => Some(Self::ProtectPlayer),
            46 => Some(Self::Shapeshift),
            47 => Some(Self::CheckMurder),
            48 => Some(Self::CheckProtect),
            49 => Some(Self::Pet),
            50 => Some(Self::CancelPet),
            51 => Some(Self::CheckZipline),
            52 => Some(Self::UseZipline),
            53 => Some(Self::TriggerSpores),
            54 => Some(Self::CheckSpore),
            55 => Some(Self::CheckShapeshift),
            56 => Some(Self::RejectShapeshift),
            60 => Some(Self::LobbyTimeExpiring),
            61 => Some(Self::ExtendLobbyTimer),
            62 => Some(Self::CheckVanish),
            63 => Some(Self::StartVanish),
            64 => Some(Self::CheckAppear),
            65 => Some(Self::StartAppear),
            _ => None,
        }
    }

    /// Returns the name of this RPC for debugging.
    pub fn name(self) -> &'static str {
        match self {
            Self::PlayAnimation => "PlayAnimation",
            Self::CompleteTask => "CompleteTask",
            Self::SyncSettings => "SyncSettings",
            Self::SetInfected => "SetInfected",
            Self::Exiled => "Exiled",
            Self::CheckName => "CheckName",
            Self::SetName => "SetName",
            Self::CheckColor => "CheckColor",
            Self::SetColor => "SetColor",
            Self::SetHat => "SetHat",
            Self::SetSkin => "SetSkin",
            Self::ReportDeadBody => "ReportDeadBody",
            Self::MurderPlayer => "MurderPlayer",
            Self::SendChat => "SendChat",
            Self::StartMeeting => "StartMeeting",
            Self::SetScanner => "SetScanner",
            Self::SendChatNote => "SendChatNote",
            Self::SetPet => "SetPet",
            Self::SetStartCounter => "SetStartCounter",
            Self::EnterVent => "EnterVent",
            Self::ExitVent => "ExitVent",
            Self::SnapTo => "SnapTo",
            Self::CloseMeeting => "CloseMeeting",
            Self::VotingComplete => "VotingComplete",
            Self::CastVote => "CastVote",
            Self::ClearVote => "ClearVote",
            Self::AddVote => "AddVote",
            Self::CloseDoorsOfType => "CloseDoorsOfType",
            Self::SetTasks => "SetTasks",
            Self::ClimbLadder => "ClimbLadder",
            Self::UsePlatform => "UsePlatform",
            Self::SendQuickChat => "SendQuickChat",
            Self::BootFromVent => "BootFromVent",
            Self::UpdateSystem => "UpdateSystem",
            Self::SetVisor => "SetVisor",
            Self::SetNamePlate => "SetNamePlate",
            Self::SetLevel => "SetLevel",
            Self::SetHatStr => "SetHatStr",
            Self::SetSkinStr => "SetSkinStr",
            Self::SetPetStr => "SetPetStr",
            Self::SetVisorStr => "SetVisorStr",
            Self::SetNamePlateStr => "SetNamePlateStr",
            Self::SetRole => "SetRole",
            Self::ProtectPlayer => "ProtectPlayer",
            Self::Shapeshift => "Shapeshift",
            Self::CheckMurder => "CheckMurder",
            Self::CheckProtect => "CheckProtect",
            Self::Pet => "Pet",
            Self::CancelPet => "CancelPet",
            Self::CheckZipline => "CheckZipline",
            Self::UseZipline => "UseZipline",
            Self::TriggerSpores => "TriggerSpores",
            Self::CheckSpore => "CheckSpore",
            Self::CheckShapeshift => "CheckShapeshift",
            Self::RejectShapeshift => "RejectShapeshift",
            Self::LobbyTimeExpiring => "LobbyTimeExpiring",
            Self::ExtendLobbyTimer => "ExtendLobbyTimer",
            Self::CheckVanish => "CheckVanish",
            Self::StartVanish => "StartVanish",
            Self::CheckAppear => "CheckAppear",
            Self::StartAppear => "StartAppear",
        }
    }
}
